version: '2'
services:
  couchdb:
    image: couchdb:1.6.1
    ports:
      - "5984:5984"
    volumes:
      - /usr/local/var/lib/couchdb
  redis:
    image: redis:3.2.5
    ports:
     - "6379:6379"
  secretin-server:
     build:
       context: .
     ports:
       - "3000:80"
     environment:
       SECRETIN_SERVER_PORT: 80
       SECRETIN_SERVER_REDIS_URL: redis://anonymous@redis:6379
       SECRETIN_SERVER_COUCHDB_URL: http://couchdb:5984/secretin
     depends_on:
       - redis
       - couchdb
